### ISSUE TITLE
Feature request - Log level limits

### ISSUE THREAD

**Issue by magikstm** [popphp/pop-log#2]
Such as:
1) A developer may wish to log all severity levels
2) A development server may wish to log only a few levels (or change that occasionnally)
3) A production server may wish to log even less levels (or change that occasionnally)

Could this feature be considered?

I looked in the code and this feature doesn't seem to be available.

**Comment by nicksagona** [comment]
Yes I think this is something we can look into implementing.

**Comment by nicksagona** [comment]
Ok @magikstm - I just pushed up to the v3-dev branch. The new code will let you set log level limits for the log writers. Check out the examples in the README file:

https://github.com/popphp/pop-log/tree/v3-dev#setting-log-limits

**Comment by magikstm** [comment]
Thanks a lot.

I tested locally by using the new branch with composer in my application.

It works perfectly.

**Comment by nicksagona** [comment]
Great I'll merge it into master and release it. Thanks.
